### ISSUE TITLE
Unable to use spring-boot-starer-temporal

### ISSUE THREAD

**Issue by fusionswap** [applicaai/spring-boot-starter-temporal#16]
Hi,
I keep getting this error NPE at below. What do I have to do to make sure activityWorkers in TemporalProperties is not null?

Caused by: java.lang.NullPointerException: null
	at ai.applica.spring.boot.starter.temporal.config.TemporalProperties.getActivityWorkers(TemporalProperties.java:107) ~[spring-boot-starter-temporal-0.7.1-SNAPSHOT.jar:na]
	at ai.applica.spring.boot.starter.temporal.config.TemporalProperties.hashCode(TemporalProperties.java:26) ~[spring-boot-starter-temporal-0.7.1-SNAPSHOT.jar:na]
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936) ~[na:1.8.0_171]

**Comment by bfugas** [comment]
Hi,

it looks like something is missing in your `application.yaml` file. Please recheck if `spring.temporal.workflows`, `spring.temporal.activityStubs` and `spring.temporal.activityWorkers` are filled in properly.

You may also try upgrading the starter library to `0.8.0-SNAPSHOT` and temporal-sdk to `1.1.0`.

**Comment by simcha** [comment]
As there is no answer and no one is having same bug I close it.
